version: '3.8'

services:
  web:
    build: ./web
    command: python3 workout_manager/app.py run -h 0.0.0.0
    ports:
      - 8888:5000
    environment:
      flask_app_db_host: db
      flask_app_db_name: postgres-docker-aug22
      flask_app_db_username: docker-user
      flask_app_db_password: 1234pass
      sql_host: db
      sql_port: 5432
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - ./web/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker-user
      POSTGRES_PASSWORD: 1234pass
      POSTGRES_DB: postgres-docker-aug22
    ports:
      - 5432:5432

volumes:
  postgres-data:
