version: '3.8'

services:
  web:
    build: .
    ports:
      - 5000:8888
    environment:
      flask_app_db_host: db
      flask_app_db_name: postgres-docker-aug22
      flask_app_db_username: docker-user
      flask_app_db_password: 1234pass
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: docker-user
      POSTGRES_PASSWORD: 1234pass
      POSTGRES_DB: postgres-docker-aug22
    ports:
      - 5432:5432

volumes:
  postgres-data:
